export const DATE_TIME_FORMAT = {
  VOUCHER_DATE_FORMAT: "HH:mm DD/MM/YYYY",
  TRANSACTION_DATE_FORMAT: "DD/MM/YYYY - HH:mm",
  EVENT_DATE_FORMAT: "YYYY-MM-DD HH:mm:ss",
  VOUCHER_DATE:"DD/MM/YYYY",
  VOUCHER_ALLOCATED_DATE_FORMAT: "DD.MM.YYYY",
  LOYALTY_RETURN_FORMAT: "DD/MM/YYYY HH:mm:ss",
};
