export const QUERY_KEY = {
  VOUCHER_LIST: "VOUCHER_LIST",
  VOUCHER_DETAIL: "VOUCHER_DETAIL",
  APP_SETTINGS: "APP_SETTINGS",
  ZALO_INFO: "ZALO_INFO",
  DEAL_LIST: "DEAL_LIST",

  /* Auth */
  LOGIN: "LOGIN",

  /* User */
  GET_USER_INFO: "GET_USER_INFO",
  GET_USER_SETTING: "GET_USER_SETTING",
  GET_ZALO_USER_INFO: "GET_ZALO_USER_INFO",
  CHECK_USER_CAN_ALLOCATE: "CHECK_USER_CAN_ALLOCATE",
  CHECK_NEW_USER: "CHECK_NEW_USER",

  /* Loyalty */
  GET_LOYALTY_CUSTOMER_DETAIL: "GET_LOYALTY_CUSTOMER_DETAIL",

  /* Location */
  GET_VIET_NAM_PROVINCE_LIST: "GET_VIET_NAM_PROVINCE_LIST",

  /* Transaction */
  GET_TRANSACTION_LIST: "GET_TRANSACTION_LIST",

  /* Scheme */
  GET_SCHEME_LIST: "GET_SCHEME_LIST",
  GET_SCHEME_DETAIL: "GET_SCHEME_DETAIL",

  /* Hot News */
  GET_HOT_NEWS_LIST: "GET_HOT_NEWS_LIST",

  /* Voucher */
  CHECK_CAN_ALLOCATE_VOUCHER: "CHECK_CAN_ALLOCATE_VOUCHER",

  /* Mix and Match */
  GET_MIX_AND_MATCH_LIST: "GET_MIX_AND_MATCH_LIST",
  GET_RANDOM_MISSION: "GET_RANDOM_MISSION",

  /* Leader Board */
  GET_LEADER_BOARD: "GET_LEADER_BOARD",

  /* Stamp */
  GET_COLLECTED_STAMPS: "GET_COLLECTED_STAMPS",

  /* CDP */
  GET_CDP_CUSTOMER: "GET_CDP_CUSTOMER",

  /* Card Flip */
  CHECK_CAN_ALLOCATE_VOUCHER_CARD_FLIP: 'CHECK_CAN_ALLOCATE_VOUCHER_CARD_FLIP',
  CHECK_CAN_SHARE_GAME_CARD_FLIP: 'CHECK_CAN_SHARE_GAME_CARD_FLIP',

  /* Merry Christmas */
  CHECK_CAN_ALLOCATE_VOUCHER_CHRISTMAS: 'CHECK_CAN_ALLOCATE_VOUCHER_CHRISTMAS',
  CHECK_CAN_SHARE_GAME_CHRISTMAS: 'CHECK_CAN_SHARE_GAME_CHRISTMAS',
  GET_LEADER_BOARD_CHRISTMAS: 'GET_LEADER_BOARD_CHRISTMAS',

  /* Gamification */
  GET_CAN_SHARE_GAME: 'GET_CAN_SHARE_GAME',
  GET_GAME_DETAIL: 'GET_GAME_DETAIL',
  GET_GAME_LEADERBOARD: 'GET_GAME_LEADERBOARD',
  GET_GAME_USER_STATS: 'GET_GAME_USER_STATS',
  GET_CAN_PLAY_GAME: 'GET_CAN_PLAY_GAME',
};
